language: node
node:  
   - '12'

services:
   - docker
before_install:
   - docker image prune --all 
   - docker-compose -f docker-compose-build.yaml build --parallel

script: 
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   - docker tag udagram-api-feed 22grace/udagram-api-feed:v1
   - docker tag udagram-api-user 22grace/udagram-api-user:v1
   - docker tag udagram-frontend 22grace/udagram-frontend:v1
   - docker tag reverseproxy 22grace/reverseproxy:v1

after_success: 
   - docker login --username 22grace --password-stdn
   - docker push 22grace/udagram-api-user:v1
   - docker push 22grace/udagram-api-feed:v1
   - docker push 22grace/reverseproxy:v1
   - docker push 22grace/udagram-frontend:v1      



