apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      run: backend-user
  replicas: 2    
  template:
    metadata:
      labels:
        run: backend-user
    spec:
      containers:
      - name: backend-user
        image: 22grace/udagram-api-user:v2
        resources:
          limits:
            memory: 2000Mi
            cpu: 1000m
          requests:
            memory: 100Mi
            cpu: 200m 
        ports:
        - containerPort: 80
