apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user-deployment
spec:
  selector:
    matchLabels:
      app: udagram-api-user
  replicas: 2    
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
      - name: udagram-api-user
        image: 22grace/udagram-api-user:v2
        resources:
          limits:
            memory: 600Mi
            cpu: 500m
          requests:
            memory: 300Mi
            cpu: 200m 
        ports:
        - containerPort: 80
