apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed-deployment
spec:
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: udagram-api-feed/v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
