apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed-deployment
spec:
  selector:
    matchLabels:
      app: udagram-api-feed
  replicas: 2    
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: 22grace/udagram-api-feed:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
