apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      app: backend-user
  replicas: 2    
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: 22grace/udagram-api-user:v2
        resources:
          limits:
            memory: 900Mi
            cpu: 500m
          requests:
            memory: 300Mi
            cpu: 200m 
        ports:
        - containerPort: 80
