apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-deployment
spec:
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: 22grace/reverseproxy:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: 1000m
          requests:
            cpu: 500m  
        ports:
        - containerPort: 80
